### PR TITLE
Allow parameter substitution for sets

### PR DESCRIPTION
**Pull request by divarvel**
It was not possible to slice whole sets directly, on set elements. Now both elements and complete sets can be sliced in.

For convenience, sets can be sliced from any `Foldable`

```haskell
creation :: IO ByteString
creation = do
  let allowedOperations = ["read", "write"] :: [Text]
      networkLocal = "192.168.0.1" :: Text
  let authority = [block|
       // this is a comment
       right("file1", ${allowedOperations});
       check if source_ip($source_ip), ["127.0.0.1", ${networkLocal}].contains($source_ip);
       |]
```

### CODE REVIEW

**Review by ptitfred — APPROVED** [review]
LGTM

**Comment by ptitfred** [comment]
It might be a newbie question but:

What's the point of the `resource` and `right` facts in the authority block if there's two checks following?

**Comment by divarvel** [comment]
The example is protracted, i wanted to showcase parameter substitution. Those extra checks would usually added later on in an extra block

**Comment by divarvel** [comment]
I have reworked the example to make it less artificial.

**Pull request merged**
